site_name: Twitivity Documentations
site_dir: docs
docs_dir: _docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate #
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  fonts:
    code: Roboto Mono
    text: Roboto
  favicon: images/favicon.png
  logo: assets/logo.png
  features:
    - header.autohide
  extra:
    homepage: https://repo.twitivity.dev/
  markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
